spring:
  application:
    name: notification-service
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    ru.alexey_ten: INFO